"use client";

import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";

import './globals.css'
import {Header} from "@/components/Header";
import {Providers} from "@/components/Providers";

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//    title: 'next-ts',
//    description: 'Generated by create next app',
// }

export default function RootLayout(
   {
      children,
   }: {
      children: ReactNode
   }) {

   return (
      <html lang="en">
      <body className={inter.className}>
      <Providers>
         <div className={'flex flex-col min-h-screen'}>
            <Header/>
            <main className={'flex-auto flex flex-col'}>
               {children}
            </main>
            {/*<Footer/>*/}
         </div>
      </Providers>
      </body>
      </html>
   )
}
