import React from "react";

import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout(
   {
      children,
   }: {
      children: React.ReactNode
   }) {
   return (
      <html lang="en">
      <body className={inter.className}>
      {/*<Providers>*/}
      <div className={'flex flex-col min-h-[100%]'}>
         {/*<Header/>*/}
         <main className={'flex-auto flex flex-col overflow-hidden pt-[4.5rem] sm:pt-[9rem]'}>
            {children}
         </main>
         {/*<Footer/>*/}
      </div>
      {/*</Providers>*/}
      </body>
      </html>
   )
}
